# Generated by Django 4.1.7 on 2023-04-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('sname', models.CharField(max_length=128)),
                ('course', models.CharField(max_length=128)),
                ('marks', models.FloatField(max_length=128)),
            ],
        ),
    ]
